spring:
  application:
    name: petchill-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.120
  session:
    store-type: redis
server:
  port: 12000