server:
  port: 10000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petchill_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: petchill-product
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.120
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 360000
      use-key-prefix: true
      cache-null-values: true

#  mvc:
#    static-path-pattern: /static/**

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.alexhong.petchill: error

petchill:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10



